# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from codeagent import orchestrator_pb2 as codeagent_dot_orchestrator__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in codeagent/orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Converse = channel.stream_stream(
                '/codeagent.v1.Orchestrator/Converse',
                request_serializer=codeagent_dot_orchestrator__pb2.HarnessMessage.SerializeToString,
                response_deserializer=codeagent_dot_orchestrator__pb2.OrchestratorMessage.FromString,
                _registered_method=True)
        self.Compact = channel.unary_unary(
                '/codeagent.v1.Orchestrator/Compact',
                request_serializer=codeagent_dot_orchestrator__pb2.CompactRequest.SerializeToString,
                response_deserializer=codeagent_dot_orchestrator__pb2.CompactionUpdate.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/codeagent.v1.Orchestrator/Health',
                request_serializer=codeagent_dot_orchestrator__pb2.Empty.SerializeToString,
                response_deserializer=codeagent_dot_orchestrator__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ReflectMemory = channel.unary_unary(
                '/codeagent.v1.Orchestrator/ReflectMemory',
                request_serializer=codeagent_dot_orchestrator__pb2.MemoryReflectionRequest.SerializeToString,
                response_deserializer=codeagent_dot_orchestrator__pb2.MemoryReflectionResponse.FromString,
                _registered_method=True)


class OrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Converse(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReflectMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Converse': grpc.stream_stream_rpc_method_handler(
                    servicer.Converse,
                    request_deserializer=codeagent_dot_orchestrator__pb2.HarnessMessage.FromString,
                    response_serializer=codeagent_dot_orchestrator__pb2.OrchestratorMessage.SerializeToString,
            ),
            'Compact': grpc.unary_unary_rpc_method_handler(
                    servicer.Compact,
                    request_deserializer=codeagent_dot_orchestrator__pb2.CompactRequest.FromString,
                    response_serializer=codeagent_dot_orchestrator__pb2.CompactionUpdate.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=codeagent_dot_orchestrator__pb2.Empty.FromString,
                    response_serializer=codeagent_dot_orchestrator__pb2.HealthResponse.SerializeToString,
            ),
            'ReflectMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ReflectMemory,
                    request_deserializer=codeagent_dot_orchestrator__pb2.MemoryReflectionRequest.FromString,
                    response_serializer=codeagent_dot_orchestrator__pb2.MemoryReflectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codeagent.v1.Orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codeagent.v1.Orchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Orchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Converse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/codeagent.v1.Orchestrator/Converse',
            codeagent_dot_orchestrator__pb2.HarnessMessage.SerializeToString,
            codeagent_dot_orchestrator__pb2.OrchestratorMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codeagent.v1.Orchestrator/Compact',
            codeagent_dot_orchestrator__pb2.CompactRequest.SerializeToString,
            codeagent_dot_orchestrator__pb2.CompactionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codeagent.v1.Orchestrator/Health',
            codeagent_dot_orchestrator__pb2.Empty.SerializeToString,
            codeagent_dot_orchestrator__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReflectMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codeagent.v1.Orchestrator/ReflectMemory',
            codeagent_dot_orchestrator__pb2.MemoryReflectionRequest.SerializeToString,
            codeagent_dot_orchestrator__pb2.MemoryReflectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
